name: DiscordStatusPlugin
main: yourpackage.DiscordStatusPlugin
version: 1.2.2
api-version: 1.21
author: nekit2123
description: Sends server status updates to Discord and manages tab prefixes.
commands:
  sos:
    description: Enable or disable SOS mode
    usage: /sos on|off
  setprefix:
    description: Set a player's tab prefix group
    usage: /setprefix <Player> <Group>
  addprefix:
    description: Create a new tab prefix group
    usage: /addprefix <Group>
  removeprefix:
    description: Remove a player's tab prefix group
    usage: /removeprefix <Player>
  setdiscord:
    description: Change Discord invite link
    usage: /setdiscord <link>
    permission: discordstatus.setdiscord
  helpplugin:
    description: Show all plugin commands
    usage: /helpplugin
permissions:
  discordstatus.setdiscord:
    description: Allows changing the Discord invite link
    default: op