default-prefix: "§7[Default] "
tablist:
  header: |
    §6§lYourServerName
    §7Welcome to the server!
    §eTPS: {tps}  §aPing: {ping}
    §bTime (Kyiv): {time_kyiv}
    §bTime (CST): {time_cst}
  footer: |
    §7Enjoy your stay!
    §fOnline: {online}/{max}
    §eDiscord: https://discord.gg/YHSYShaM3A
  size: 80 # максимальное количество слотов в табе
  
  
#Пояснения:
#header/footer — текст вверху и внизу таба, поддерживает переменные:
#{tps} — TPS сервера
#{ping} — пинг игрока
#{time_kyiv} — время в Киеве
#{time_cst} — время в CST
#{online} — онлайн игроков
#{max} — максимальное количество слотов
#size — максимальное количество слотов, отображаемых в табе
#groups — оформление префиксов для груп
groups:
  owner:
    prefix: "§c[⍟] §f"
  moderator:
    prefix: "§9[⚔] §f"
  VIP:
    prefix: "§a[❤] §f"
  default:
    prefix: "§7[ᐅ] §f"